---
- hosts: smarthome
  become: true
  gather_facts: true
  any_errors_fatal: true

  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5

  roles:
    - role: os
      tags:
        - os

    - role: geerlingguy.security
      tags:
        - security

    # - role: geerlingguy.firewall
    #   tags:
    #     - security
    #     - firewall

    # - role: security
    #   tags:
    #     - security
    #     - endlessh

    # - role: geerlingguy.pip
    #   tags:
    #     - python

    # - role: geerlingguy.docker
    #   tags:
    #     - docker
